config/routes.rb
HoursReport::Application.routes.draw do

  class XHRConstraint
    def matches?(request)
      !request.xhr? && !(request.url =~ /\.json$/ && ::Rails.env == 'development') && (request.url =~ /users\/\d+\/expense_reports\//)
    end
  end

  get '/users/:user_id/expense_reports*path' => 'expense_reports#index', :constraints => XHRConstraint.new

  root 'users#show'
  concern :the_role, TheRole::AdminRoutes.new

  namespace :admin do
    concerns :the_role
  end

  resources :invitations,       only: [:new, :create]
  resources :users,             only: [:index, :show] do
    resources :timesheets,      only: [:edit, :update, :index]
    resources :expense_reports, only: [:index, :new, :edit]
  end

  resources :expense_reports, module: 'admin' do
    collection do
      get :reset_filterrific
    end
  end

  match "users/all" => "users#update_all", :as => :update_all, :via => :put

  resources :reports,        only: [:index, :show, :new, :create, :destroy, :update] do
    resources :timesheets,   only: [:edit, :update, :index]
    resources :reminders,    only: [:create]
  end

  match '/auth/:provider/callback' => 'sessions#create', via: %i(get post)
  match '/logout'                  => 'sessions#destroy', via: %i(get delete), as: :logout
  match '/login'                   => 'sessions#new', via: %i(get), as: :login

  mount Sidekiq::Web => '/sidekiq'

  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      resources :rates, only: [:index]
      resources :expenses
      resources :expense_reports do
        resources :expenses
      end
    end

    namespace :v2 do
      get 'current_timesheet', to: 'timesheets#current_timesheet'
    end
  end
end

app/views/shared/_admin_links.html.haml
%li.dropdown.green
  %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
    = fa_icon "user 3x"
    %p Users
  %ul.dropdown-menu
    %li
      = link_to  new_invitation_path, target: "_self" do
        %i.fa.fa-envelope.fa-2x
        %p Invite a new user
    %li
      = link_to users_path, target: "_self" do
        %i.fa.fa-users.fa-2x
        %p All Users

%li.dropdown.orenge
  %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
    = fa_icon "calendar 3x"
    %p Reports
  %ul.dropdown-menu
    %li
      = link_to new_report_path, target: "_self" do
        %i.fa.fa-plus.fa-2x
        %p New Report
    %li
      = link_to reports_path, target: "_self" do
        %i.fa.fa-files-o.fa-2x
        %p All Reports
    - if Report.current_report
      %li
        = link_to Report.current_report, target: "_self" do
          %i.fa.fa-file-text-o.fa-2x
          %p Current Report

app/views/shared/_flash_messages.html.haml
#alert-container

- flash.each do |type, message|
  %div{class: "alert #{bootstrap_class_for(type)} alert-dismissable fade in"}
    %button.close{"data-dismiss" => "alert"} ×
    = message

app/views/shared/_footer.html.haml
.container
  %p.text-muted.credit
    - unless current_user.andand.current_timesheet.andand.submitted?
      .time-left-to-submit-timesheet

app/views/shared/_google_tag_manager.html.haml
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-KRJWG6"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-KRJWG6');</script>
<!-- End Google Tag Manager -->

app/views/shared/_navbar.html.haml
#main-header.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
    - if current_user
      .navbar-collapse.collapse{style: "height: 1px;"}
        %ul.nav.navbar-nav.navbar-left
          = render 'shared/user_links'

          - if current_user.admin?
            = render 'shared/admin_links'

        %ul.nav.navbar-nav.navbar-right
          %li
            %h1= Time.now.strftime('%b %d, %Y')
          %li.pink
            = link_to logout_path, target: "_self" do
              = fa_icon "sign-out 3x"
              %p Sign Out
          %li.pink
            = link_to current_user, :target => "_self", :class => '', :title => "#{current_user.name}" do
              = image_tag current_user.image || "http://lorempixel.com/100/100/cats/", :size => "70x70", :class => "img-rounded"

app/views/shared/_user_links.html.haml
- if current_user.timesheets.exists?
  %li.dropdown.purple
    %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
      = fa_icon "clock-o 3x"
      %p Timesheets
    %ul.dropdown-menu
      %li
        = link_to "All your timesheets", user_timesheets_path(current_user), target: "_self"
      - if current_user.current_timesheet
        %li
          = link_to "Your current timesheet", [:edit, current_user, current_user.current_timesheet], target: "_self"
          .current-timesheet-ending-time.hidden= current_user.current_timesheet.end_date.strftime("%Y/%m/%d")
%li.dropdown.indianred
  %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
    = fa_icon "plane 3x"
    %p Expense Report
  %ul.dropdown-menu
    %li
      = link_to user_expense_reports_path(current_user), target: "_self" do
        = fa_icon "files-o 2x"
        %p Your expense reports
    %li
      = link_to new_user_expense_report_path(current_user), target: "_self" do
        = fa_icon "files-o 2x"
        %p New expense reports
    - if current_user.admin?
      %li
        = link_to expense_reports_path, target: "_self" do
          = fa_icon "files-o 2x"
          %p All expense reports