config/routes.rb
HoursReport::Application.routes.draw do

  class XHRConstraint
    def matches?(request)
      !request.xhr? && !(request.url =~ /\.json$/ && ::Rails.env == 'development') && (request.url =~ /users\/\d+\/expense_reports\//)
    end
  end

  get '/users/:user_id/expense_reports*path' => 'expense_reports#index', :constraints => XHRConstraint.new

  root 'users#show'
  concern :the_role, TheRole::AdminRoutes.new

  namespace :admin do
    concerns :the_role
  end

  resources :invitations,       only: [:new, :create]
  resources :users,             only: [:index, :show] do
    resources :timesheets,      only: [:edit, :update, :index]
    resources :expense_reports, only: [:index, :new, :edit]
  end

  resources :expense_reports, module: 'admin' do
    collection do
      get :reset_filterrific
    end
  end

  match "users/all" => "users#update_all", :as => :update_all, :via => :put

  resources :reports,        only: [:index, :show, :new, :create, :destroy, :update] do
    resources :timesheets,   only: [:edit, :update, :index]
    resources :reminders,    only: [:create]
  end

  match '/auth/:provider/callback' => 'sessions#create', via: %i(get post)
  match '/logout'                  => 'sessions#destroy', via: %i(get delete), as: :logout
  match '/login'                   => 'sessions#new', via: %i(get), as: :login

  mount Sidekiq::Web => '/sidekiq'

  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      resources :rates, only: [:index]
      resources :expenses
      resources :expense_reports do
        resources :expenses
      end
    end

    namespace :v2 do
      get 'current_timesheet', to: 'timesheets#current_timesheet'
    end
  end
end

app/models/report.rb
class Report < ActiveRecord::Base
  has_many :timesheets, dependent: :destroy
  has_many :reminders, dependent: :destroy
  has_many :users, :through => :timesheets
  has_many :expense_reports, :through => :timesheets

  validates :current, uniqueness: true, if: "current?"
  validates_date :start_date, :end_date

  validates :status, inclusion: { in: %w(open submitted reopened) }
  validates_associated :timesheets
  validates :start_date, :end_date,
    :overlap => { :message_title => :overlapping,
                  :message_content => "There is an overalapping report for the given dates" }
  validate :timesheets_submitted, :if => :submitted?

  scope :unsubmitted, -> { where.not(:status => "submitted") }

  after_create :extract_tenbis_usage
  after_create :extract_on_call
  after_update :update_expense_reports, :if => :status_changed?

  delegate :submitted?, :open?, :reopened?, :to => :status

  def self.build_report(report_data)
    report = new(report_data)
    if report.start_date && report.end_date
      report.tenbis_date = Date.parse report_data["tenbis_date"]
      report.timesheets = Timesheet.build_timesheets(
        User.active, report.start_date, report.end_date
      )
    end
    report
  end

  def self.current_report
    find_by(:current => true)
  end

  def self.prepare_next
    if Report.not_first?
      Report.new(:start_date => last_end_date + 1.day, :end_date => last_end_date + 1.month, :tenbis_date => last_tenbis_date + 1.month)
    else
      Report.new
    end
  end

  def self.last_end_date
    Report.order(:end_date => :desc).first.end_date
  end

  def self.last_tenbis_date
    Report.order(:tenbis_date => :desc).first.tenbis_date
  end

  def add_new_user(user)
    self.timesheets << Timesheet.build_timesheets([user], self.start_date, self.end_date)
    TenbisUsageCollector.perform_in(2.minutes, self.id)
  end

  def update_expense_reports
    if submitted?
      self.expense_reports.each(&:archive!)
    elsif reopened?
      self.expense_reports.each(&:approve!)
    end
  end

  def timesheet_summaries
    users.map do |user|
      timesheet = timesheets.find_by(user: user)
      summary.new(timesheet.id,
                  timesheet.user_id,
                  timesheet.user_name,
                  timesheet.user.employee_number,
                  timesheet.total_hours,
                  timesheet.vacation_days,
                  timesheet.sickness_days,
                  timesheet.army_reserve_days,
                  timesheet.leave_of_absence_days,
                  timesheet.tenbis_usage,
                  timesheet.expenses_abroad,
                  timesheet.on_call_compensation,
                  timesheet.status,
                  timesheet.comments_number)
    end

  end

  def status
    status = read_attribute(:status) || ''
    status.inquiry
  end

  private

  def self.not_first?
    Report.count > 0
  end

  def summary
    Struct.new(:id,
               :user_id,
               :user_name,
               :employee_number,
               :total_hours,
               :vacation_days,
               :sickness_days,
               :army_reserve_days,
               :leave_of_absence_days,
               :tenbis,
               :expenses_abroad,
               :on_call_compensation,
               :status,
               :comments_number)
  end

  def extract_tenbis_usage
    TenbisWorker.perform_async(self.tenbis_date.month, self.tenbis_date.year)
    TenbisUsageCollector.perform_in(2.minutes, self.id)
  end

  def extract_on_call
    OnCallWorker.perform_async(self.id)
  end

  def timesheets_submitted
    self.timesheets.each do |timesheet|
      return errors[:base] << "Report cannot be submitted due to unsubmitted timesheets" unless timesheet.submitted?
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  respond_to :xls, :html

  before_action :login_required
  before_action :role_required

  def index
    @reports = Report.all
  end

  def show
    @report = Report.find(params[:id])
    respond_to do |format|
      format.html
      format.xls { doc_raptor_send }
    end
  end

  def new
    @report = Report.prepare_next
  end

  def create
    @report = Report.build_report(report_params)

    if @report.save
      redirect_to reports_path, :notice => "Report created"
    else
      render "new"
    end
  end

  def update
    @report = Report.find(params[:id])

    if @report.update_attributes(report_params)
      redirect_to @report, :notice => "Report #{@report.status}"
    else
      flash[:alert] = "Action failed"
      render 'show'
    end
  end

  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    redirect_to reports_path
  end

  private

  def report_params
    params.require(:report).permit(:start_date, :end_date, :current, :tenbis_date, :status)
  end
end

app/views/reports/index.html.haml
.row
  %table.table.hoverable-row#reports
    %tr
      %th.hidden
      %th From
      %th To
      %th Status
      %th Actions
    - @reports.each do |report|
      %tr{ :class => ("warning" if report.current?) }
        %td.hidden
          = link_to "Details", report
        %td= report.start_date.strftime('%B %d, %Y')
        %td= report.end_date.strftime('%B %d, %Y')
        %td= report.status
        %td
          = link_to "", report, :class => 'glyphicon glyphicon-trash', :method => :delete, :confirm => "Are you sure?" unless report.current?

app/views/reports/new.html.haml
%h1 New Report
.well.col-sm-offset-3.col-sm-6
  = simple_form_for @report, :html => { :class => "form-horizontal" } do |f|
    .form-group
      = f.label :start_date, { class: "col-sm-3" }
      .col-sm-9
        = f.text_field :start_date, { class: 'datepicker form-control', :value => f.object.start_date.andand.strftime('%B %d, %Y') }
        = f.error :start_date
    .form-group
      = f.label :end_date, { class: "col-sm-3" }
      .col-sm-9
        = f.text_field :end_date, { class: 'datepicker form-control', :value => f.object.end_date.andand.strftime('%B %d, %Y') }
        = f.error :end_date
    .form-group
      = f.label :tenbis_date, "10bis month", { class: "col-sm-3 control-label" }
      .col-sm-9
        = f.text_field :tenbis_date, { class: 'month-datepicker form-control', :value => f.object.tenbis_date.andand.strftime('%B %Y') }
        = f.error :tenbis_date
    .form-group
      = f.label :current, { class: "col-sm-3" }
      .col-sm-9
        = f.input_field :current, { checked: true }
        = f.error :current
    .form-group
      .col-sm-offset-3.col-sm-9
        = f.error :overlapping
        = f.submit "Create Report", class: "btn btn-primary"

app/views/reports/show.html.haml
.action-header
  - unless @report.reload.submitted?
    = simple_form_for [@report, Reminder.new] do |f|
      = f.submit "Send Reminders", :class => "btn btn-default"

  - if @report.reload.submitted?
    = link_to image_tag('excel_icon.ico', :size => '25x25'), report_path(@report, format: "xls"), :class => "btn btn-default pull-right", :title => "Export to Excel"

  = simple_form_for @report, :html => { :class => "form-horizontal" } do |f|
    - change_status_to = @report.reload.submitted? ? "reopened" : "submitted"
    = f.hidden_field :status, :value => change_status_to
    - unless @report.reload.submitted?
      = f.submit "Submit Report", :class => "btn btn-success"
      = f.hidden_field :current, :value => false
    - else
      = f.submit "Reopen Report", :class => "btn btn-success"
    = f.error :base

.panel.panel-default
  .panel-heading
    %h4= "#{@report.start_date.strftime('%B %d, %Y')} - #{@report.end_date.strftime('%B %d, %Y')}"
  %table.table
    %thead
      %tr
        %th Name
        %th Total hours
        %th Vacation Days
        %th Sickness Days
        %th Army Reserve Days
        %th LOA Days
        %th 10Bis
        %th Expenses Abroad
        %th On Call Compensation
        %th Status
        %th Comments
    %tbody
      = render :partial => "timesheets/summary", :collection =>  @report.timesheet_summaries, :as => :summary

app/views/reports/show.xls.haml
%table{ :name => "Excel Example", :style => "background-color:#DADFE8; border-color:black" }
  %tr{ :style => "font-weight:bold; background-color:#C27BA0" }
    %th Name
    %th Vacation Days
    %th Sickness Days
    %th Army Reserve Days
    %th Leave of absence Days
    %th 10Bis
    %th Expense report - local
    %th Expense report - abroad
    %th On Call Compensation
    %th New Employee (start date)
    %th Comments
  = render :partial => "timesheets/summary", :collection =>  @report.timesheet_summaries, :as => :summary